# Generated by Django 3.2.5 on 2021-07-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=200)),
                ('field_1', models.CharField(blank=True, max_length=200)),
                ('field_2', models.CharField(blank=True, max_length=200)),
                ('field_3', models.CharField(blank=True, max_length=200)),
                ('field_4', models.CharField(blank=True, max_length=200)),
                ('field_5', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('acct_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_by', models.CharField(max_length=200)),
                ('request_email', models.CharField(max_length=200)),
                ('date_required', models.DateTimeField(blank=True, verbose_name='Date required')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_org', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_user', models.CharField(max_length=200)),
                ('customer_pass', models.CharField(max_length=200)),
                ('field_1', models.CharField(blank=True, max_length=200)),
                ('field_2', models.CharField(blank=True, max_length=200)),
                ('field_3', models.CharField(blank=True, max_length=200)),
                ('field_4', models.CharField(blank=True, max_length=200)),
                ('field_5', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct.accounttypes')),
            ],
        ),
    ]
