apiVersion: v1
kind: ConfigMap
metadata:
  name: account-request-config
  labels:
    app: account-request
data:
  POSTGRES_HOST_AUTH_METHOD: "trust"
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "ThisPasswordShouldBeChanged"
  DJANGO_SECRET_KEY: "JustARandomStringOfCharacters"
  DJANGO_DEBUG: "True"
  DATABASE_URL: postgres://postgres:ThisPasswordShouldBeChanged@127.0.0.1:5432/postgres
    #DATABASE_URL: 'sqlite:////tmp/db.sqlite3'
